Repository UnBArqDsw2024-2/2024.2_G7_Entrega_Entrega_02, pull requests merged in 2024-11, with the labels that each got.

#22 Léxico
  docs/Modelagem/Extra/Lexicos.md
  docs/_sidebar.md
Labels: documentation, artefact, EXTRA

#24 Cenários
  docs/Modelagem/Extra/2.5.IniciativasExtras.md
  docs/Modelagem/Extra/Cenarios/cenarios.md
  docs/Modelagem/Extra/Cenarios/introducao.md
  docs/Modelagem/Requisitos/baseline.md
  docs/_sidebar.md
Labels: documentation, artefact, EXTRA

#21 Elicitação por Entrevistas
  docs/Modelagem/Extra/Baseline.md
  docs/Modelagem/Extra/Elicitacao/Elicitacao.md
  docs/Modelagem/Extra/Elicitacao/Entrevistas.md
  docs/Modelagem/Extra/Elicitacao/assets/anotacoes-entrevista-2.jpg
  docs/Modelagem/Extra/Elicitacao/assets/anotaçõesDaReuniao.jpeg
  docs/_sidebar.md
Labels: documentation, artefact, EXTRA

#25 Diagrama de Componentes
  docs/Modelagem/ModelagemDinamica/2.2.1.Diagrama_de_atividades.md
  docs/Modelagem/ModelagemEstatica/DiagramaComponentes.md
  docs/Modelagem/ModelagemEstatica/assets/cart-payment-section.png
  docs/Modelagem/ModelagemEstatica/assets/exemplo-componente.png
  docs/Modelagem/ModelagemEstatica/assets/exemplo-contexto.png
  docs/Modelagem/ModelagemEstatica/assets/exemplo-dependencia.png
  docs/Modelagem/ModelagemEstatica/assets/exemplo-modal.png
  docs/Modelagem/ModelagemEstatica/assets/exemplo-pagina.png
  docs/Modelagem/ModelagemEstatica/assets/favorites-section.png
  docs/Modelagem/ModelagemEstatica/assets/login-home-notifications-section.png
  docs/Modelagem/ModelagemEstatica/assets/myorders-section.png
  docs/Modelagem/ModelagemEstatica/assets/profile-section.png
  docs/Modelagem/ModelagemEstatica/assets/search-details-section.png
  docs/_sidebar.md
Labels: documentation, FOCO 1, artefact

#28 Diagrama de Classes
  docs/Modelagem/ModelagemEstatica/DiagramaClasses.md
  docs/Modelagem/ModelagemEstatica/assets/brainstorming-classes.png
  docs/Modelagem/ModelagemEstatica/assets/diagrama-de-classes.png
  docs/_sidebar.md
Labels: documentation, FOCO 1, artefact

#29 Criação da modelagem ágil, com o backlog do projeto e a priorização das histórias de usuário.
  docs/Modelagem/Extra/2.5.IniciativasExtras.md
  docs/Modelagem/Extra/ModelagemAgil/Backlog.md
  docs/Modelagem/Extra/ModelagemAgil/Priorizacaous.md
  docs/_sidebar.md
Labels: documentation, artefact, EXTRA

#34 Diagrama de estados
  docs/Modelagem/ModelagemDinamica/DiagramaDeEstados.md
  docs/_sidebar.md
  docs/assets/Diagrama de Estados.jpg
Labels: documentation, FOCO 3, artefact

#27 Especificação Suplementar
  docs/Modelagem/Extra/especificacao-suplementar.md
  docs/_sidebar.md
Labels: documentation, artefact, EXTRA

#35 Diagrama Modelo Relacional
  docs/Modelagem/Extra/DiagramaModeloRelacional.md
  docs/Modelagem/Extra/assets/Modelo_Relacional.png
  docs/_sidebar.md
Labels: documentation, artefact

#33 Criação dos diagramas de atividades
  docs/Modelagem/ModelagemDinamica/2.2.1.Diagrama_de_atividades.md
  docs/Modelagem/ModelagemDinamica/assets/image-1.png
  docs/Modelagem/ModelagemDinamica/assets/image-2.png
  docs/Modelagem/ModelagemDinamica/assets/image-3.png
  docs/Modelagem/ModelagemDinamica/assets/image-4.png
  docs/Modelagem/ModelagemDinamica/assets/image-5.png
  docs/Modelagem/ModelagemDinamica/assets/image-6.png
  docs/Modelagem/ModelagemDinamica/assets/image.png
  docs/_sidebar.md
Labels: documentation, artefact

#23 Validação do Protótipo
  docs/Modelagem/Extra/ValidacaoPrototipo.md
  docs/Modelagem/Extra/assets/Perguntas orientadoras da entrevista validadora do protótiopo.pdf
  docs/_sidebar.md
Labels: documentation, artefact, EXTRA

#32 Criação do documento de diagrama de sequência, criação e adição dos diagramas no documento.
  docs/Modelagem/ModelagemDinamica/2.2.1.DiagramaSequencia.md
  docs/Modelagem/ModelagemDinamica/assets/exemplo-destruicao.png
  docs/Modelagem/ModelagemDinamica/assets/exemplo-entidade.png
  docs/Modelagem/ModelagemDinamica/assets/exemplo-especificacao.png
  docs/Modelagem/ModelagemDinamica/assets/exemplo-fragmento.png
  docs/Modelagem/ModelagemDinamica/assets/exemplo-linha-de-vida.png
  docs/Modelagem/ModelagemDinamica/assets/exemplo-metodo.png
  docs/Modelagem/ModelagemDinamica/assets/sequencia-cadastro.png
  docs/Modelagem/ModelagemDinamica/assets/sequencia-conta.png
  docs/Modelagem/ModelagemDinamica/assets/sequencia-login.png
  docs/Modelagem/ModelagemDinamica/assets/sequencia-logout.png
  docs/Modelagem/ModelagemDinamica/assets/sequencia-pagamento.png
  docs/Modelagem/ModelagemDinamica/assets/sequencia_pedido.png
  docs/_sidebar.md
Labels: documentation, FOCO 2, artefact

#30 Criação do diagrama e das especificações dos casos de uso relacionados ao cliente.
  docs/Modelagem/ModelagemOrganizacional/2.3.1.CasosDeUsoCliente.md
  docs/Modelagem/ModelagemOrganizacional/assets/CasosDeUsoCliente.drawio.png
  docs/_sidebar.md
Labels: documentation, FOCO 3, artefact

#39 Casos de Uso - Geral e da Loja
  docs/Modelagem/ModelagemOrganizacional/DiagramaCasosDeUsoCliente.md
  docs/Modelagem/ModelagemOrganizacional/DiagramaCasosDeUsoGeral.md
  docs/Modelagem/ModelagemOrganizacional/DiagramaCasosDeUsoLoja.md
  docs/Modelagem/ModelagemOrganizacional/DiagramaCasosdeUsoEntregador.md
  docs/Modelagem/ModelagemOrganizacional/assets/casos-de-uso-geral.png
  docs/Modelagem/ModelagemOrganizacional/assets/casos-de-uso-loja.png
  docs/_sidebar.md
Labels: documentation, FOCO 3, ambient
